# Generated by Django 5.2.5 on 2025-08-19 02:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Descriptive title of the task (maximum 200 characters)', max_length=200, verbose_name='Title')),
                ('description', models.TextField(blank=True, help_text='Detailed description of the task (optional)', null=True, verbose_name='Description')),
                ('status', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_progreso', 'En Progreso'), ('completada', 'Completada')], default='pendiente', help_text='Current status of the task', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the task was created', verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time of the last update', verbose_name='Updated at')),
                ('completed_at', models.DateTimeField(blank=True, help_text='Date and time when the task was marked as completed', null=True, verbose_name='Completed at')),
                ('user', models.ForeignKey(help_text='Owner of the task', on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
                'db_table': 'tasks',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='tasks_user_id_a53e17_idx'), models.Index(fields=['created_at'], name='tasks_created_db4e37_idx'), models.Index(fields=['status'], name='tasks_status_031d4c_idx')],
            },
        ),
    ]
